[build]
  command = "npm install --prefix eps-api && npm run build --prefix eps-api"
  publish = "static"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
