[siteInfo]
id = "533c0dba-00ad-47de-9dfd-ed42dd829ce"

[build]
command = "npm run build"
commandOrigin = "config"
publish = "/opt/build/repo/static"
publishOrigin = "config"
functionsDirectory = "/opt/build/repo/netlify/functions"

[build.environment]
OPENAI_API_KEY = "your_api_key_here"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[functions]
directory = "netlify/functions"