[build]
  command = "cd ../eps-api && npm install && npm run build"
  publish = "../static"
  functions = "netlify/functions"

[context.production.environment]
  OPENAI_API_KEY = "your-openai-api-key"